name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/NISTtheDocs2Death@fused
        with:
          docs-folder: docs/
          pre-build-command: |-
            echo "doc/source/_static"
            && ls docs/
            && echo `pwd`
